### ISSUE TITLE
slug checking should be case insensitive

### ISSUE THREAD

**Issue by tmtmtmtm** [ciudadanointeligente/write-it#1012]
When we check if a proposed slug is already taken we ignore case, so if 'eduskunta' is already taken, and I ask for 'eDuSkUnTa', it'll bypass the "that already exists", and create eduskunta-2 instead.

**Comment by chrismytton** [comment]
This should be fixed by changing [this line](https://github.com/ciudadanointeligente/write-it/blob/e1ddc39d83624b08db2816814ad852dc7f0ef2f9/nuntium/user_section/forms.py#L209) to the following:

```python
slug_exists = WriteItInstance.objects.filter(slug__iexact=slug).exists()
```

which does a case-insensitive search for existing slugs.
