### ISSUE TITLE
Copy amends on your_instances

### ISSUE THREAD

**Issue by MyfanwyNixon** [ciudadanointeligente/write-it#1046]
1. On the "your_instances" page my copy reads "Use the menu on the left " but actually when you're on that page, you don't see the full menu. It needs to say:
 >  Click on 'edit' and then use the menu on the left.

2. "contact us to let us know" on the same page should be a link.

**Comment by schlos** [comment]
Problem listed under point 2 is related to https://github.com/ciudadanointeligente/write-it/issues/1040

**Comment by tmtmtmtm** [comment]
#652 is also done, so I think this can be closed.
