### ISSUE TITLE
Can't view English versions of sites 

### ISSUE THREAD

**Issue by tmtmtmtm** [ciudadanointeligente/write-it#1092]
Going to http://parliament-of-finland.writeinpublic.com/ redirects to /hu

Trying to go directly to /en 404s

**Comment by lfalvarez** [comment]
Done!

**Comment by tmtmtmtm** [comment]
@lfalvarez : Great, thanks. It's a little concerning that whatever you had to do to fix this didn't involve anything that's actually in the repo, though…

**Comment by lfalvarez** [comment]
@tmtmtmtm it was a configuration thing, in which I had commented "English".
