### ISSUE TITLE
Switching between translations when creating an instance

### ISSUE THREAD

**Issue by trickvi** [ciudadanointeligente/write-it#1093]
When I click on "Create your own site" on: http://writeinpublic.com/en/ the language switches all of a sudden to Hungarian (even if the button link states it should be English).

A friend in a different country has also tested this and hits this bug as well.

This might be related to #1086

**Comment by tmtmtmtm** [comment]
Hi @trickvi — apologies for this. I suspect this is indeed to do with a temporary fix we added related to the Hungarian site in #1086, but that should have been removed by now. Hopefully @lfalvarez will be able reset that …

**Comment by lfalvarez** [comment]
Hey there has this been fixed? I can't seem to replicate the problem.

**Comment by tmtmtmtm** [comment]
This seems to have been fixed — if not please reopen!
