### ISSUE TITLE
"CSV importer at EveryPolitician" link 404s

### ISSUE THREAD

**Issue by henare** [ciudadanointeligente/write-it#1100]
http://everypolitician.org/upload/

![selection_001](https://cloud.githubusercontent.com/assets/48945/10625417/bad93fb6-77ee-11e5-9e13-2dea6fce3afa.png)

**Comment by lfalvarez** [comment]
Hey there!
First of all thanks for reporting this, and second I think that EveryPolitician is accepting data as described in this page -> http://everypolitician.org/submitting.html. I could not find any place more suitable to change the link. Or is there @chrismytton @tmtmtmtm ?

**Comment by tmtmtmtm** [comment]
Nice timing — @duncanparkes, @chrismytton, and I are working together today on completely changing this part of the process today. Watch this space…

**Comment by lfalvarez** [comment]
Perfect! :+1:

**Comment by henare** [comment]
Thanks @tmtmtmtm.

>Hi @henare — were you actually hoping to create a WIP site, or was this just something you stumbled across whilst playing? If the former, would it be with data that's already in EveryPolitician, or do you have your own Popolo for the contacts?

It was the latter.

The data I wanted to play with isn't in EveryPolitician.

**Comment by tmtmtmtm** [comment]
Ah, that's not going to be easy then, as we discovered doing #1102. In theory you should be able to point WriteIt at any suitably formatted Popolo, but in practice that "suitably formatted" is quite restrictive, in that it needs to be in a format that [popit-django](https://github.com/mysociety/popit-django) can query: in particular it needs to be able to respond to a "/persons" call that returns a list of all the relevant people, each of whom will need at least one Membership without an end_date embedded into it, and a contact details section (even if that's blank, for reasons we couldn't quite work out.)  I believe @lfalvarez plans to switch all that to using [django-popolo](https://github.com/openpolis/django-popolo) instead, which would hopefully make all that simpler, but for now you're going to have to marshall your Popolo into a similar format we used for our adapter.

**Comment by henare** [comment]
You just read my mind @tmtmtmtm. I was going to submit an issue to ask what "suitably formatted" Popolo meant :) This is super-useful, thank you.

**Comment by tmtmtmtm** [comment]
Fixed by https://github.com/ciudadanointeligente/write-it/pull/1102
