### ISSUE TITLE
Cannot create a new instance at writeinpublic.com

### ISSUE THREAD

**Issue by michalskop** [ciudadanointeligente/write-it#1104]
I am trying to create a new instance at writeinpublic.com.

When I get to http://writeinpublic.com/en/writeitinstance/create I enter the address of my json file http://test.kohovolit.sk/m/dev/persons.json and some name (`plasy-2014` in my case).

But the `Create` button is still disabled.

**Comment by michalskop** [comment]
I created it later by selecting some of the proposed parliaments and than changing it to my file. However if I fall into `Create` being disabled, I could not get it enabled any more. (I had to start again, reloading the page.)

**Comment by tmtmtmtm** [comment]
I can't replicate this when starting from scratch; however, if I do try to create `plasy-2014` it tells me that that's already taken (rightly), but then won't let me 'Create' once I change that to something else.

**Comment by struan** [comment]
Fixed in 036364f715c7604c41d787bb051a2163e6fd9214
