### ISSUE TITLE
Easier selection of recipient names

### ISSUE THREAD

**Issue by paullenz** [ciudadanointeligente/write-it#195]
The tick box method of name selection is great if there are only a couple of names, but if there are hundreds it won't really work.  Could the selection be from a drop down list, with auto-complete text entry

**Comment by tmtmtmtm** [comment]
Is this still an issue, or is what's there at the minute now enough?

**Comment by tmtmtmtm** [comment]
The requested version here is done. We can open a new ticket for any further improvements to it.
