### ISSUE TITLE
"Report this message" button

### ISSUE THREAD

**Issue by paullenz** [ciudadanointeligente/write-it#200]
Could we add a button against both public message and responses for users to report message that they believe to be offensive etc

The admin interface will list all reported message with the option available for the admin user to hide or mark as okay as appropriate

**Comment by lfalvarez** [comment]
Here I think it would be interesting to understand something:
What if a user wanted to hide a message for no reason. Could he do so? if a user could then the action of hiding a message should be in a separate issue.

**Comment by tmtmtmtm** [comment]
Anyone should be able to *report* a message as needing attention, but only the administrator will be able to hide them.

**Comment by chrismytton** [comment]
Could this potentially be done with a simple `mailto:` link which just emails admin@writeitpublic.com or whatever?

**Comment by tmtmtmtm** [comment]
@chrismytton :+1:

**Comment by lfalvarez** [comment]
I think we could maybe close this in favour of #713
