### ISSUE TITLE
Use cuttlefish

### ISSUE THREAD

**Issue by lfalvarez** [ciudadanointeligente/write-it#373]
Given that cuttlefish has recently [open to be used as a service](http://poplus.org/posts/email-is-your-secret-weapon/) we should move our service to use cuttlefish instead of Amazon ses

**Comment by tmtmtmtm** [comment]
@lfalvarez Do you have an estimate of how much work is still required on this one?

**Comment by lfalvarez** [comment]
I'd say a day or less

**Comment by paullenz** [comment]
Ooo - that is *very* good news!

**Comment by lfalvarez** [comment]
I'm having a slight problem with the encoding in cuttlefish. I've been in contact with Matthew and he'll be seeing it soon.

**Comment by lfalvarez** [comment]
This is pretty much ready and working! =)

**Comment by tmtmtmtm** [comment]
Woohoo!

**Comment by lfalvarez** [comment]
I think it would be worth adding a couple of send the admins an email if everything fails before closing this.
