### ISSUE TITLE
Cope with downloading from large PopIts

### ISSUE THREAD

**Issue by lfalvarez** [ciudadanointeligente/write-it#375]
When the popit instance is too big then some times throws a 504 error, at pulling people from popit. It can be fixed by using a different thread to do the pulling from popit api.

**Comment by tmtmtmtm** [comment]
What's the current state of this one? Is this problem still occurring?

**Comment by lfalvarez** [comment]
@tmtmtmtm this problem is no longer happening =). I'm closing this issue.
