### ISSUE TITLE
Write-it pulling people from popit does not work if the url is provided with HTTPS

### ISSUE THREAD

**Issue by lfalvarez** [ciudadanointeligente/write-it#382]
For example if the url is provided using https://pmocl.popit.mysociety.org/api/v0.1/ it does not pull anyone, on the other hand if this url is provided then it works ok http://pmocl.popit.mysociety.org/api/v0.1/.

Thanks to @schlos for reporting.

**Comment by duncanparkes** [comment]
I wonder if you're suffering from the same thing which we were on SayIt before we installed some extra python and system packages:

https://github.com/mysociety/sayit.mysociety.org/commit/e69c7d2b760e4c18faea43f456f12243bbcfa597

**Comment by lfalvarez** [comment]
:smile: it does work it is the same problem :smile:  thanks a lot
