### ISSUE TITLE
Language per instance

### ISSUE THREAD

**Issue by lfalvarez** [ciudadanointeligente/write-it#390]
Possibility for setting a language per instance:

Related issues:
* #388

**Comment by duncanparkes** [comment]
If I were making an instance of WriteIt for here in Wales I think I'd prefer it if a single instance could handle both Welsh and English and change everything based on browser configuration or otherwise user selected language.

**Comment by lfalvarez** [comment]
=) that's good to know. Then I could probably close this issue.

**Comment by lfalvarez** [comment]
This issue might not be necessary and we could just use the browser configurtion
