### ISSUE TITLE
Resync with PopIt at regular intervals

### ISSUE THREAD

**Issue by tmtmtmtm** [ciudadanointeligente/write-it#397]
Ideally the interval should be configurable on a per-instance basis, but it might be OK at first to just pick a period (say weekly), and people can manually re-sync inbetween.

Having an out-of-band fetcher like this would also mean that other places that currently fetch (with possible timeouts etc), could be changed to just pushing a 'due: now' onto this stack. ( #375 #411 )

**Comment by lfalvarez** [comment]
As #413 was merged it closes this issue
