### ISSUE TITLE
Use Photos from PopIt

### ISSUE THREAD

**Issue by tmtmtmtm** [ciudadanointeligente/write-it#399]
If the PopIt instance contains photos, display them.

**Comment by tmtmtmtm** [comment]
@lfalvarez: Does the current PopIt import mechanism make this information available to us, or will we need to change how importing works to be able to have this?

**Comment by tmtmtmtm** [comment]
ping @lfalvarez

**Comment by lfalvarez** [comment]
Currently we have the image_url stored in the Person model, so we would have to define where is it that we want the images to be displayed and probably we would need something like [Pillow](https://pypi.python.org/pypi/Pillow/2.7.0) to process the images and display them. I'd say **hours**.

**Comment by duncanparkes** [comment]
Can we just deep link to the images on PopIt?
