### ISSUE TITLE
Provide better default message templates

### ISSUE THREAD

**Issue by tmtmtmtm** [ciudadanointeligente/write-it#408]
Should explain where the message is coming from, and that replies will be published online.

**Comment by duncanparkes** [comment]
@MyfanwyNixon Is going to have a look at the wording on these for us, and I'll then integrate that back in.

**Comment by MyfanwyNixon** [comment]
Here y'go: https://docs.google.com/a/mysociety.org/document/d/14-1hjGBJ00GJv6v0mhm53GKn_v_mAU7_Yqel03C7fNs/edit

**Comment by tmtmtmtm** [comment]
Closed by #594

**Comment by tmtmtmtm** [comment]
Closed by #594
