### ISSUE TITLE
By default, only show plain text templates for emails

### ISSUE THREAD

**Issue by tmtmtmtm** [ciudadanointeligente/write-it#409]
Currently an instance administrator needs to supply separate text and HTML versions for each of the three different email templates.

**Comment by paullenz** [comment]
my immediate reaction given the MVP approach would be to say plain text
only?

**Comment by tmtmtmtm** [comment]
The code for setting an HTML version already exists, so there's no real need to remove it. However, to make things simple, I propose that the Admin `Templates` page only offers, by default, a plain text version. If someone wants to also have an HTML version, that can be exposed through an 'advanced' version.

(We'll need to make sure that having no HTML template Does The Right Thing, rather than sending an empty version!)

**Comment by duncanparkes** [comment]
HTML emails only look good if they're worked on quite hard. I think we should remove the default HTML email template and use a data migration to remove that from any instances that use it. We can leave in (in a very advanced settings kind of place) the ability to add a custom HTML email templates.

**Comment by lfalvarez** [comment]
I think that this could make things a lot simpler for users as well.
