### ISSUE TITLE
Set default 'active' flag per recipient depending on Membership status

### ISSUE THREAD

**Issue by tmtmtmtm** [ciudadanointeligente/write-it#419]
a Person who only has Memberships that are no longer active, should be disabled by default.

**Comment by tmtmtmtm** [comment]
Requires #434 first.

**Comment by tmtmtmtm** [comment]
This should remove any Memberships that are no longer active, and make sure there's at least one still live.

**Comment by lfalvarez** [comment]
If a person does not have memberships then the contact should be active?

**Comment by tmtmtmtm** [comment]
If *no-one* has memberships, then anyone with an email address should be active. But if generally people have memberships, and person X doesn't, then I don't think they should be automatically active (the admin could manually set them so, of course)

**Comment by duncanparkes** [comment]
I added a test for a membership with neither a start nor an end date, but not for anything related to people with no memberships.
