### ISSUE TITLE
What should we do if a linked PopIt vanishes?

### ISSUE THREAD

**Issue by tmtmtmtm** [ciudadanointeligente/write-it#420]
If an underlying PopIt instance no longer exists, what should happen?

**Comment by paullenz** [comment]
Ooo - that is a good question

Ideally I would say it should keep working using the details it already
has, rather than fall over and die

**Comment by tmtmtmtm** [comment]
@lfalvarez — what will currently happen in this case? Will things just keep working (and we can close this), or will there be a problem?

**Comment by tmtmtmtm** [comment]
Current behaviour is that that the re-poll will show an error, and the admin can decide what to do.

#725 will also add a better "Deactivate".
