### ISSUE TITLE
Turn off "create an answer" link by default

### ISSUE THREAD

**Issue by tmtmtmtm** [ciudadanointeligente/write-it#426]
In most instances, admins won't be creating answers. Only enable this option if an 'advanced options' flag is set.

**Comment by lfalvarez** [comment]
Hey I just noted that the guys at nouabook are using this feature, so I think it is a good thing to delay it.

**Comment by tmtmtmtm** [comment]
The idea wasn't to remove the feature, but to only display it on sites that enable it (so that it's not confusing for the majority of instances that don't need it). So we could just ensure that it's switched on for Nouabook.
