### ISSUE TITLE
Handle more than text/plain replies

### ISSUE THREAD

**Issue by tmtmtmtm** [ciudadanointeligente/write-it#428]
We currently don't handle:
- [ ] text/html
- [ ] multipart/mixed
- [ ] multipart/alternative

**Comment by tmtmtmtm** [comment]
@lfalvarez am I remembering correctly that all incoming emails are now at least *stored*, rather than discarded?

**Comment by lfalvarez** [comment]
Some of the parts besides attachments (#557) are:

* multipart/mixed
* multipart/alternative
* text/html

This is not the end of the list, but in the meantime I'm investigating what each one of them are.

**Comment by lfalvarez** [comment]
I have found that some other parts are: 

* message/delivery-status: This is the status for a delivery, for example a bounce
* multipart/report: This is the explanation for the former
* message/rfc822: In the emails that I have use for testing this are for wraping the original message.

These three kinds of messages IMO are not worth of parsing.

**Comment by tmtmtmtm** [comment]
If we don't parse bounce messages (for example), what will happen in those cases?

**Comment by lfalvarez** [comment]
We are handling bounce messages. We look for the contact to which it was sent to and mark it as bounced, that sends an email to the owner of the instance telling her/him that the contact was bounced. =)

**Comment by tmtmtmtm** [comment]
What appears on the public message page on the site at that point? Do we make it obvious that there's been a bounce?

**Comment by lfalvarez** [comment]
oH! currently we are just noticing the owner of the instance, but not the public in general, we could turn that into an issue.

**Comment by lfalvarez** [comment]
Ok, I've got it: The method [walk()](https://docs.python.org/2/library/email.message.html#email.message.Message.walk) goes through all the significant parts of the email.
All the significant parts of the email are simply 'text/plain' and 'text/html'.

**Comment by duncanparkes** [comment]
Closing this in favour of #595 and #557, which handle everything that's left, I think.
