### ISSUE TITLE
See all messages from a person

### ISSUE THREAD

**Issue by tmtmtmtm** [ciudadanointeligente/write-it#442]
Even though there's no actual user account, we can simulate this, as they're all from confirmed email addresses.

**Comment by lfalvarez** [comment]
My question here would be: are there not any problems with publishing the emails of the people that had confirmed?. In the sense that we would probably have a url to see all the messages from a person like ```eduskunta/from/copy@paste.org```?

There  would be another way to approach this. And it would be by storing the sender (author) in a different model and not display the email anywhere.

**Comment by lfalvarez** [comment]
I'm thinking that we could probably use a url like ```<instance_slug>/from_the_same_author as/<message_slug>/``` and if that is the approach then we would not have to display the author's email anywhere.

**Comment by lfalvarez** [comment]
about this @chrismytton what do you think? as it is kind of related to #605

**Comment by tmtmtmtm** [comment]
I've no strong opinions on how we implement this, but we absolutely shouldn't be leaking the email address of the sender.

**Comment by lfalvarez** [comment]
I'd go for the second one as probably it is way simpler than storing the author as a separate entity, but I wouldn't be against that either.

**Comment by tmtmtmtm** [comment]
Another alternative is to a one-way hash of the email address

**Comment by lfalvarez** [comment]
uhh sorry I took the message approach already. We could get back to this
