### ISSUE TITLE
Typo in some english help wording

### ISSUE THREAD

**Issue by mlandauer** [ciudadanointeligente/write-it#471]
On page for writing an email it says
> Trailing * means that we don't have how to contact the person

Should it instead say "Trailing * means that we don't know how to contact the person"?

The word "have" should be replaced by "know".

**Comment by lfalvarez** [comment]
Thanks a lot for the comments I think that we're removing this part so we don't display any person without comments.

**Comment by tmtmtmtm** [comment]
Removed in #677
