### ISSUE TITLE
Make very clear everywhere that messages are public

### ISSUE THREAD

**Issue by lfalvarez** [ciudadanointeligente/write-it#485]
they should be **VERY** explicit in:

* [x] The web form #730  
* [x] The mail to which an official will respond #408

**Comment by tmtmtmtm** [comment]
Connected to #408

**Comment by zarino** [comment]
Pull request for the first half of this ticket (clear message in the writing form itself) here: https://github.com/ciudadanointeligente/write-it/pull/772
