### ISSUE TITLE
Latin-2 characters are not displayed correctly

### ISSUE THREAD

**Issue by schlos** [ciudadanointeligente/write-it#512]
Some Latin-2 characters in [iso-8859-2](http://en.wikipedia.org/wiki/ISO/IEC_8859-2) gets replaced with question mark (?) character.

What WriteIt gets from PopIt via API:

```

{
      "html_url": "https://zagreb.popit.mysociety.org/persons/548d637a446a57290ed8540e",
      "sources": [],
      "images": [],
      "initials": "",
      "url": "https://zagreb.popit.mysociety.org/api/v0.1/persons/548d637a446a57290ed8540e",
      "id": "548d637a446a57290ed8540e",
      "start_date": null,
      "end_date": null,
      "birth_date": null,
      "death_date": null,
      "founding_date": null,
      "dissolution_date": null,
      "name": "Ratko Maričić",
      "memberships": [
        {
          "html_url": "https://zagreb.popit.mysociety.org/memberships/548d6384446a57290ed85410",
          "url": "https://zagreb.popit.mysociety.org/api/v0.1/memberships/548d6384446a57290ed85410",
          "person_id": "548d637a446a57290ed8540e",
          "role": "Gradski zastupnik",
          "organization_id": "548d56d4446a57290ed853d1",
          "start_date": "",
          "end_date": "",
          "area": {
            "name": ""
          },
          "id": "548d6384446a57290ed85410",
          "links": [],
          "contact_details": []
        }
      ],
      "links": [],
      "contact_details": [],
      "identifiers": [],
      "other_names": []
    },

```

Name in JSON field `"name": "Ratko Maričić"` will be displayed in WriteIt form as `Ratko Mari?i?`.

WriteIt instance:
http://writeit.ciudadanointeligente.org/en/writeit_instances/zagreb-local-government

**Comment by lfalvarez** [comment]
Got it! it is because currently we're using MySql as our database (I know it is the worse choice ever made), and it doesn't use utf8 right out of the box and therefore it stores that sort of data in a wrong way. So my choice of things to do would be to encourage to move to PostgreSQL. In the meantime I'm correcting this problems in the database so I  can close this in favor of a "Use PostgreSQL issue"

**Comment by lfalvarez** [comment]
closing in favour of #513

**Comment by schlos** [comment]
Thanks!
I forgot there is one issue already opened for that #383. I looked but couldn't find it.

Thanks for linking issues!
