### ISSUE TITLE
Encourage instance creation on an empty install.

### ISSUE THREAD

**Issue by duncanparkes** [ciudadanointeligente/write-it#517]
On a WriteIt installation which doesn't yet have any instances, it would be better for the page at `/instances` to say 'Would you like to create an instance?' to encourage the new install owner, rather than just listing 0 instances.

**Comment by tmtmtmtm** [comment]
Added (sort-of) in bddf05f4ad8084b6c4c5f2c6eb96c4b7a3f320e3; Being linked up in #864
