### ISSUE TITLE
No way to get to public version of instance from admin?

### ISSUE THREAD

**Issue by tmtmtmtm** [ciudadanointeligente/write-it#524]
There doesn't seem to be an obvious way to get from the admin pages of an instance to the public view of it.

**Comment by lfalvarez** [comment]
Uhhh yeah that's right it's kind of obviously needed and it is not there!

**Comment by lfalvarez** [comment]
is it in the django admin? or in the list of instances that you get as a normal user?

**Comment by tmtmtmtm** [comment]
You can't get from, say, http://writeit.ciudadanointeligente.org/en/writeitinstance/edit/1815 to http://writeit.ciudadanointeligente.org/en/writeit_instances/eduskunta-2

The simplest fix is probably just to make the final entry in the mini-header a link:

  Home / Your profile / Your instances / Eduskunta
