### ISSUE TITLE
Standardise URL naming

### ISSUE THREAD

**Issue by tmtmtmtm** [ciudadanointeligente/write-it#525]
Sometimes we have URLs like /en/writeitinstance/edit/1814; other times we have /en/writeit_instances/eduskunta-2/messages/test-106

**Comment by duncanparkes** [comment]
Suggested url structure:

`/` &rarr; Overview
`/settings` &rarr; General settings
`/settings/api` &rarr; API configuration
`/settings/sources` &rarr; Popit URLs
`/settings/templates` &rarr; Edit message tremplates
`/recipients` &rarr; People that can be written to
`/messages` &rarr; Includes bounces/spam/pending, etc.

**Comment by duncanparkes** [comment]
I think this is finished - any things we've missed we can open new issues for.
