### ISSUE TITLE
Gmail sends confirmation emails to Spam

### ISSUE THREAD

**Issue by tmtmtmtm** [ciudadanointeligente/write-it#527]
“Why is this message in Spam? We've found that lots of messages from writeit.ciudadanointeligente.org are spam”

**Comment by lfalvarez** [comment]
I just found that out, I think it might have to do with the content or the sender. What do you say?

**Comment by tmtmtmtm** [comment]
This is probably one for @flupsy...

**Comment by Flupsy** [comment]
Could you arrange to send a message to me at ian@mysociety.org ?

**Comment by tmtmtmtm** [comment]
@lfalvarez I can't think of a way to set @Flupsy as a recipient, other than adding him as a contact in PopIt, and then resyncing with that (and turning my instance live so that the email goes to him, rather than me-as-administrator). Is there another way? Or is this something you can quickly make a database level change for just for a one-off test?

**Comment by lfalvarez** [comment]
This can be done in at a database level, could you tell me who to look for?

**Comment by tmtmtmtm** [comment]
This was actually much easier than I was thinking above: I just had to send a message giving @flupsy's email address as if it were mine, so that he would be prompted to confirm that it was really him.

**Comment by lfalvarez** [comment]
And how did it go?

**Comment by tmtmtmtm** [comment]
I was hoping you'd fill that in, as you were part of the conversation with @Flupsy, and had various things to investigate from it, IIRC?

**Comment by Flupsy** [comment]
If memory serves the only odd thing I could see was that the envelope sender didn't match the `From:` line.  Apparently you can fix that in SES.

**Comment by tmtmtmtm** [comment]
There was also something about multiple DKIM headers, and not having a _domainkey record

**Comment by Flupsy** [comment]
I found that multiple DKIM headers is OK, but not having a _domainkey 
record isn't so OK.

-- 
Ian Chard   <ian@mysociety.org>
mySociety systems administrator   http://www.mysociety.org/

**Comment by tmtmtmtm** [comment]
Multiple DKIM is OK as in "nothing will have a problem with it"? Or in "technically it's not disallowed, but Here Be Dragons!"?

**Comment by Flupsy** [comment]
As I understand it, it's pretty standard.

**Comment by tmtmtmtm** [comment]
Now that we're going via Cuttlefish, at least some of this seems to have been resolved.

Not sure what things we can do or check before actually closing this, though...

**Comment by lfalvarez** [comment]
I'll wait a little longer to see what happens but if you're not having problems anymore that's a success!

**Comment by tmtmtmtm** [comment]
Closing this for now. We can reopen if the issue reappears.
