### ISSUE TITLE
Duplicate email template files

### ISSUE THREAD

**Issue by duncanparkes** [ciudadanointeligente/write-it#531]
There are two pairs of identical email confirmation template files:

nuntium/templates/nuntium/mails/confirm.txt
nuntium/templates/nuntium/mails/confirm.html
nuntium/templates/nuntium/mails/confirmation/content_template.html
nuntium/templates/nuntium/mails/confirmation/content_template.txt

I'm guessing that one of these is current, and that the other is left over from before a refactor.

**Comment by lfalvarez** [comment]
this is related to #417, #409 and #408
