### ISSUE TITLE
Wireframe and implement wireframes for public-facing WriteIt pages (Design)

### ISSUE THREAD

**Issue by paullenz** [ciudadanointeligente/write-it#539]
Work out the layout for WriteIt, wireframe it and implement the basic wireframe (i.e. don't make it pretty at this stage)

**Comment by lfalvarez** [comment]
:heart: :+1:

**Comment by zarino** [comment]
Wireframes of the key public pages here: https://drive.google.com/file/d/0B_2LN3vVyLmAMmw1RGF0d1FKdFU/view
