### ISSUE TITLE
Wireframe and implement wireframes for WriteIt admin pages (Design)

### ISSUE THREAD

**Issue by paullenz** [ciudadanointeligente/write-it#540]
Work out the layout for WriteIt back end, wireframe it and implement the basic wireframe (i.e. don't make it pretty at this stage)

**Comment by wrightmartin** [comment]
Current progress (pages are out of order, it's Overview -> Settings -> Data Sources -> API)

https://drive.google.com/open?id=0B9zzRX6aqtSiVTlxbGd2ZFdjaFU&authuser=0

**Comment by tmtmtmtm** [comment]
More thoughts at #824
