### ISSUE TITLE
Disassociate a WriteIt from a PopIt.

### ISSUE THREAD

**Issue by duncanparkes** [ciudadanointeligente/write-it#561]
There is currently no way to disassociate a WriteIt from a PopIt. Once you've associated it, you're going to have all those people in your WriteIt forever, as things stand.

**Comment by tmtmtmtm** [comment]
#483 will enable you to turn off the sync, but we'll also need a way to make the people no longer active. (Also a slight overlap with #419)

**Comment by tmtmtmtm** [comment]
Closing in favour of #725
