### ISSUE TITLE
No way to alter the autosync setting

### ISSUE THREAD

**Issue by duncanparkes** [ciudadanointeligente/write-it#562]
Currently any PopIt linked to a WriteIt is autosynced. There is a setting to turn off autosyncing, but access is to it is not provided anywhere as yet.

Once we allow turning off autosyncing, we'll need to have a way for the syncing to be done manually. You could do it at the moment by putting the same PopIt url in and relating it again, but that's decidedly unlovely.

**Comment by tmtmtmtm** [comment]
See also #610

**Comment by tmtmtmtm** [comment]
Closed by #695
