### ISSUE TITLE
META: Moderation process

### ISSUE THREAD

**Issue by martinszy** [ciudadanointeligente/write-it#582]
Hi, I just recieved a message in which the user included his personal information. I'm not sure this is what he wanted.
So I clicked the button "moderate" in order to accept or reject the message, and I find that "moderate" means "accept". So I would recommend changing the term here.

Also, I would like to edit the message so it doesn't include the user's personal information (phone). Also, there is no way to unpublish the message once it's accepted.

If you see the message:
http://writeit.ciudadanointeligente.org/es/message/1558/answers

There's this menu at the bottom "Person	  Content	  Actions" with no apparent functionality.

**Comment by tmtmtmtm** [comment]
Thanks! I've split out separate tickets for each of these, all of which are definitely important to fix.

**Comment by martinszy** [comment]
Ok, so we close this?

**Comment by duncanparkes** [comment]
@tmtmtmtm Can you link those issues in and then close this one?

**Comment by tmtmtmtm** [comment]
I had already linked them, but I was leaving this open for now to see if there were any other related issues to do with Moderation.
