### ISSUE TITLE
Remove references to local popit

### ISSUE THREAD

**Issue by chrismytton** [ciudadanointeligente/write-it#600]
Currently the writeit tests run against a local version of popit-api, using the [`mysociety-deploy`](https://github.com/mysociety/popit-api/tree/mysociety-deploy) branch, which was last updated in 2013.

For the time being it seems simplest to run the tests against the staging popit site, the tests will be slower, but at least we'll be testing against a recent version of popit.

**Comment by chrismytton** [comment]
Currently a lot of the tests call `popit_load_data` in `global_test_case.py`, which in turn calls `popit-api-for-testing/node_modules/.bin/mongofixtures` in the git repo that is created by the `start_local_popit_api.bash` script. So the fixtures need to be moved into python so a popit instance can be created on the staging site from the fixtures in `nuntium/tests/fixtures/*`.

I've made a start on this here - https://github.com/ciudadanointeligente/write-it/compare/master...mysociety:600-remove-local-popit - but there's still quite a bit more that needs doing before the tests will pass properly on that branch.

**Comment by lfalvarez** [comment]
That sounds pretty good as popit could keep on changing, but should be a bit slower, does it make sense to use a mock up of the popit-api *if needed*, like a definition in settings.py?

**Comment by chrismytton** [comment]
@lfalvarez Yea I think eventually it would be good to either mock the popit API or use something like [vcrpy](https://github.com/kevin1024/vcrpy) to record http requests and reply them. But for the time being I think it's ok to have slightly slower tests while we get things working :)

**Comment by lfalvarez** [comment]
:+1:
