### ISSUE TITLE
Update front-end url structure

### ISSUE THREAD

**Issue by chrismytton** [ciudadanointeligente/write-it#605]
Issue https://github.com/ciudadanointeligente/write-it/issues/525 is to track updating the existing admin urls, this issue is for creating a standard structure for the front-end urls.

#### The Plan

All the front-end urls start with the instance `:slug`. If/when we switch to using subdomains for the instances we can move the slug out of the url. Slugs are a minimum of 4 characters long and need to be valid for use as a subdomain. This matches what popit does so should make it easier to import from a popit instance etc.

#### URL structure

- `/:slug` &rarr; Home page for an instance
- `/:slug/write/who` &rarr; Select recipients for the message
- `/:slug/write/draft` &rarr; Screen for drafting the message to send
- `/:slug/write/preview` &rarr; Preview of the message before sending
- `/:slug/write/sign` &rarr; Screen telling you that a confirmation email has been sent, telling user to click link in the email to proceed
- `/:slug/write/sign/:token` &rarr; Confirmation url, included in the email, once user clicks this link the email is sent
- `/:slug/thread/:id` &rarr; User is redirected here after they have confirmed their email address. This contains the message that was sent along with any replies. This url is also the permalink for a message, so the user can bookmark it and come back at any time.
- `/:slug/from/:id` &rarr; List of messages sent from a user
- `/:slug/to/:id` &rarr; List of messages to a politician

**Comment by lfalvarez** [comment]
:+1:

**Comment by duncanparkes** [comment]
#197 will be done when we commit this.
