### ISSUE TITLE
Profile editing doesn't appear to work

### ISSUE THREAD

**Issue by wrightmartin** [ciudadanointeligente/write-it#608]
![profile editor 2015-04-08 at 15 14 07](https://cloud.githubusercontent.com/assets/57483/7047081/256e92cc-de02-11e4-9c7a-b43cf901b364.png)

The password box here is an input box, but it's not obvious what happens when you submit it (especially as there's no submit!)

We should make this page simply a viewer (with no password at all), and bring back editing properly later. (#443)

**Comment by tmtmtmtm** [comment]
Connected to #443 — this one (AIUI) is noting that the page is actually a form that doesn't seem to work; this one is about adding more fields into that form.
