### ISSUE TITLE
Have a configurable number of maximum recipients

### ISSUE THREAD

**Issue by tmtmtmtm** [ciudadanointeligente/write-it#609]
Allow instance owners to configure how many recipients a single message can be sent to. This should be restricted to a relatively low number (5? 10?), except by approval of a super-admin.

**Comment by lfalvarez** [comment]
and by super-admin you mean the owner of the instance?

**Comment by tmtmtmtm** [comment]
no — that's just the admin, and we want to restrict them from setting the number too high without being authorised first. The super-admin is you :)

**Comment by lfalvarez** [comment]
oh! cool!

**Comment by duncanparkes** [comment]
Fixed in 563a41
