### ISSUE TITLE
Configuration of re-polling Popit(s)

### ISSUE THREAD

**Issue by tmtmtmtm** [ciudadanointeligente/write-it#610]
Each associated PopIt can/will be re-polled at regular intervals, and your contacts updated accordingly.

Therefore we need to enable admins to:

- [ ] Turn auto-polling on/off
- [ ] Configure how often auto-polling happens
- [ ] Manually re-poll

There should not be a 'delete' concept for this behind the scenes, but we might want to simulate that in the front end.

**Comment by lfalvarez** [comment]
I'm thinking that there could be a set of fixed periods of time, ie: never, twice a day, daily, weekly

**Comment by lfalvarez** [comment]
by setting the value of periodicity, we could get rid of the concept of "Turning off the autosync" by saying: "Never do it".
