### ISSUE TITLE
"Delete" a message should just be "Hide"

### ISSUE THREAD

**Issue by tmtmtmtm** [ciudadanointeligente/write-it#611]
We shouldn't (under normal circumstances) ever be deleting messages (see also #593), so the "Delete" link in the Admin should just be "Hide" (presumably be re-toggling "Public")

**Comment by lfalvarez** [comment]
oh! that's something close to a question I had in #200

**Comment by chrismytton** [comment]
Fixed by https://github.com/ciudadanointeligente/write-it/pull/693
