### ISSUE TITLE
allow AJAX-populated modals for help links on admin pages

### ISSUE THREAD

**Issue by davewhiteland** [ciudadanointeligente/write-it#614]
Investigate and implement basic mechanism for links on admin pages to retrieve help text (from static, centralised -- that is, not running on the instance) and display as a pop-up.

Benefit is quick explanation of e.g., input field, without leaving page/new window (like a weightier tooltip).

Presumably this is a JavaScript intercepting clicks on links to the help docs, and retrieving just that section and displaying it as a modal, with option to turn this behaviour off.

This was discussed in the context of it being potentially useful in other projects if we can see it works. I think it requires a little bit of forethought in the help docs themselves, allowing named sections of help pages to be returned, and some fairly straightforward jiggerypokery at the client end.

A little bit experimental.

**Comment by lfalvarez** [comment]
How does this look like: [http://usablica.github.io/intro.js/](http://usablica.github.io/intro.js/)

I guess it doesn't make sense in all contexts, but it could in some.

**Comment by zarino** [comment]
I believe @davewhiteland has started on this in the [help-pages-within-app](https://github.com/ciudadanointeligente/write-it/tree/help-pages-within-app) branch (with data being pulled from the documentation pages in the [gh-pages-help](https://github.com/ciudadanointeligente/write-it/tree/gh-pages-help) branch).

I'm assigning this to myself now, as the pop-up bubbles need styling, and someone with bootstrap and jquery knowledge needs to refactor the code and assess whether the thing should be made to work without bootstrap.

**Comment by zarino** [comment]
Pull request for a new Bootstrap-driven (but not Bootstrap-reliant) iteration over here: https://github.com/ciudadanointeligente/write-it/pull/900

**Comment by tmtmtmtm** [comment]
#900 is merged and live, so closing this one.
