### ISSUE TITLE
Allow users to Edit/Update/Delete data sources

### ISSUE THREAD

**Issue by wrightmartin** [ciudadanointeligente/write-it#627]
(delete shouldn't delete anything - maybe just hide the recipients?)

**Comment by tmtmtmtm** [comment]
Edit probably doesn't make a lot of sense either — other than in the polling interval. 

People should disable one PopIt instance and add another one, rather than swapping one for the other inplace.

**Comment by tmtmtmtm** [comment]
See also #610

**Comment by tmtmtmtm** [comment]
Closed by #695
