### ISSUE TITLE
Design for flash messages on front-end

### ISSUE THREAD

**Issue by chrismytton** [ciudadanointeligente/write-it#630]
I've added the flash messages back in to `base_public.html` in https://github.com/ciudadanointeligente/write-it/commit/c1019c73ea30fc56c82eae9a687afd7491b82e04. These will probably need a tiny bit of design attention.

**Comment by zarino** [comment]
@chrismytton – when do these flash messages appear?

(I don't mean *technically* when, I mean which user actions do they appear in response to)

**Comment by chrismytton** [comment]
@zarino They don't appear on an instance at all anymore, I removed them in https://github.com/ciudadanointeligente/write-it/commit/cc2aed5bd0741b797ea55e235ee8f0402f63d59e. They now only appear in the manager section, which already has styles for the flash messages.
