### ISSUE TITLE
When you sign out, go to WriteIt homepage

### ISSUE THREAD

**Issue by wrightmartin** [ciudadanointeligente/write-it#633]
At the moment it goes to logged_out.html, and there's nothing we can do there that adds value at this stage

**Comment by duncanparkes** [comment]
This should hopefully be fixed in 4eec3e40123e42e9637e5d5e70ee9b34b08a79b8, but I can't test now as login is broken - sigh. I'll see if I can fix that next.

**Comment by duncanparkes** [comment]
I've merged this onto new_designs.
