### ISSUE TITLE
WriteInPublic admin section

### ISSUE THREAD

**Issue by wrightmartin** [ciudadanointeligente/write-it#642]
https://github.com/ciudadanointeligente/write-it/tree/write-in-public-design

These commits are straight onto writeit, and need to be seperated

**Comment by tmtmtmtm** [comment]
#824 might remove the need for WriteInPublic to override any of the WriteIt admin.

**Comment by tmtmtmtm** [comment]
Anything we _do_ need to change will be available after #679
