### ISSUE TITLE
Double message on /en/write/sign/ is confusing

### ISSUE THREAD

**Issue by tmtmtmtm** [ciudadanointeligente/write-it#649]
We have both a top bar of "Please confirm your email address. We have sent a confirmation link to ..." *and* a body of "Thanks, your message will be sent once you click the confirmation link in your email".

We only need one of these.

**Comment by zarino** [comment]
Yes, the django flash at the top should be removed.

![screen shot 2015-03-30 at 11 37 13](https://cloud.githubusercontent.com/assets/739624/6895471/7f6052b0-d6d8-11e4-8326-063af2e64755.png)

**Comment by tmtmtmtm** [comment]
Pretty sure this has been fixed now, though I can't quickly find where.
