### ISSUE TITLE
Problems with email a Recipient gets

### ISSUE THREAD

**Issue by tmtmtmtm** [ciudadanointeligente/write-it#661]
- [x] Subject line should just be the subject line 
- [x] Should use the instance name (and URL) instead of WriteIt
- [x] the explanation is backwards: instead of saying "you've received a message", it should say "X has sent you a message"
- [x] Then there's no need to include the Subject and From — we can just display the body
- [x] Should be say "you should reply" rather than "you can reply" :)
- [x] We should simply drop the "All the best, The WriteIt team" bit.
- [ ] URLs are broken
- [x] Should show the URL of the thread, not just of the site
- [x] Weird spacing and formatting throughout

---

Subject: `[WriteIT] Message: Test`
```
Dear Stubb Alexander

You’ve received a message via WriteIt, the online service that allows
anyone to write to politicians and other prominent people.


The message is as follows:
Subject: Test
From: Tony
Message body:
Test. Please ignore.


You can respond to Tony
simply by replying to this email.

** IMPORTANT ** Note that, as well as being sent to
Tony,
your response will be added to the
Eduskunta website at http://writeit.ciudadanointeligente.orghttp://eduskunta-2.writeit.ciudadanointeligente.org/en/,
where it will be public and visible to anyone.


If there’s a better email address for you, please let us know at
tony@mysociety.org,
where we’ll also be happy to answer any questions or problems.


All the best,
The WriteIt team
```

**Comment by duncanparkes** [comment]
Fixing this is going to require more data migrations to tidy up the existing templates, but that's OK, as I've done those before and they can just be largely copied (making sure not to introduce the repr problem again).

The linebreaks were chosen in an attempt to avoid lines getting over 72 characters when the fields were filled in. A better way to do this would be to use `textwrap` from the python standard library to get the linebreaks in the right place.

URLs have obviously been broken as a result of the move to subdomains.

**Comment by duncanparkes** [comment]
Look at nuntium migrations 57 and 58 and use something like a combination of the two to update existing templates.
