### ISSUE TITLE
Recipients Manager design

### ISSUE THREAD

**Issue by wrightmartin** [ciudadanointeligente/write-it#664]
![screen shot 2015-03-27 at 17 15 35](https://cloud.githubusercontent.com/assets/2292925/6872980/edda8624-d4a4-11e4-8791-ee4c9dbba239.png)

Shows name, email and status (are they contactable, still in office, etc)

Also: total number, errors and missing data!

**Comment by tmtmtmtm** [comment]
See also #752

**Comment by tmtmtmtm** [comment]
Overtaken by other changes.
