### ISSUE TITLE
show nice status of popits

### ISSUE THREAD

**Issue by wrightmartin** [ciudadanointeligente/write-it#665]
![screen shot 2015-03-27 at 17 17 59](https://cloud.githubusercontent.com/assets/2292925/6873026/3a8581f4-d4a5-11e4-84d3-fd76ec14e058.png)

Coloured blobs and that.

**Comment by tmtmtmtm** [comment]
Is there a wireframe for how the configurable polling intervals will hook into this?

See also #627 and #610

**Comment by wrightmartin** [comment]
@tmtmtmtm no, but I'll make one

**Comment by wrightmartin** [comment]
- Is the polling interval the only thing we want to change?

![screen shot 2015-03-30 at 11 20 53](https://cloud.githubusercontent.com/assets/2292925/6894561/e2b24846-d6ce-11e4-8863-4d80e9242e42.png)

**Comment by tmtmtmtm** [comment]
This is what appears when you click "Edit"?

From https://github.com/ciudadanointeligente/write-it/commit/1dbfcd742afea0887626edd45dbc0253e8364544 the current options for how often to re-poll are:
* Never
* Twice every Day
* Daily
* Weekly

The first of these would also take care of 'Disconnect' — and probably also 'Delete'.

We probably also need a manual "Repoll now"

**Comment by wrightmartin** [comment]
Thanks, here's an updated wireframe

When you click _edit_ this slides out from the bottom with a little touch of JS. 

![screen shot 2015-03-30 at 12 39 42](https://cloud.githubusercontent.com/assets/2292925/6895618/0cade122-d6da-11e4-88a4-34d2ef960f13.png)

**Comment by tmtmtmtm** [comment]
Looks good! :+1:

**Comment by tmtmtmtm** [comment]
I'm wondering about having "Add a new data source" so prominent, though — in the majority of cases, there'll only ever be one source, so I'd be tempted to move this to the bottom, and/or make it also be a clicky slide-out thingy.

**Comment by wrightmartin** [comment]
yeah, that sounds reasonable

**Comment by tmtmtmtm** [comment]
Closed by #695
