### ISSUE TITLE
Sort out line length on default instance homepage description

### ISSUE THREAD

**Issue by zarino** [ciudadanointeligente/write-it#671]
Hard-code a linebreak after "power." ?

![screen shot 2015-03-30 at 11 45 40](https://cloud.githubusercontent.com/assets/739624/6894927/67c235de-d6d2-11e4-808b-bf59ddfaec64.png)

**Comment by tmtmtmtm** [comment]
Are we expecting people to add their own linebreaks in when they create their description? (And thus need to make sure that that's documented on the edit page) Or is there something we can do more generally to make a better guess at where to wrap?

**Comment by zarino** [comment]
> Are we expecting people to add their own linebreaks in when they create their description?

I don't think so (unless @chrismytton @duncanparkes are happy with the HTML sanitation that'd require?) – I'm mostly just thinking about the default content, which we at least *do* have control over.

> Is there something we can do more generally to make a better guess at where to wrap?

CSS doesn't give us much help here.

The minimal trick I usually perform is to replace the last ` ` space character with an `&nbsp;`, to make sure you don't get a single orphan word on its own line.

**Comment by tmtmtmtm** [comment]
Fixed by adding explicit `br` tags.
