### ISSUE TITLE
Different "web-based" vs "API-based" creation processes

### ISSUE THREAD

**Issue by tmtmtmtm** [ciudadanointeligente/write-it#679]
Most instances will either be predominantly API-driven, or Web-driven — offer two different creation processes, each of which sets the relevant config options to sensible defaults for that approach.

**Comment by chrismytton** [comment]
Need to add two extra settings, `WEB_BASED` and `API_BASED`. These can be set independently, but most often one will be set to `True` and the other to `False`. Setting both to the same boolean value will have undefined behaviour.
