### ISSUE TITLE
Manager: Moderate button may or may not work

### ISSUE THREAD

**Issue by wrightmartin** [ciudadanointeligente/write-it#688]
/manage/messages/ 

If it does work, it doesn't give any feedback that it's done anything

**Comment by chrismytton** [comment]
The moderate button now does a full page refresh, rather than submitting via javascript. The actual issue is explained in https://github.com/ciudadanointeligente/write-it/issues/704, so I'm going to close this ticket in favour of that one.

**Comment by chrismytton** [comment]
> The moderate button now does a full page refresh, rather than submitting via javascript.

…and therefore you should now be able to at least see the error message when you click the button.
