### ISSUE TITLE
Message thread design tweaks needed

### ISSUE THREAD

**Issue by chrismytton** [ciudadanointeligente/write-it#702]
A couple of bits of styling needed for the message thread and the mini threads.

#### Spacing on the `/threads` page

![screen shot 2015-04-02 at 11 47 43](https://cloud.githubusercontent.com/assets/22996/6962747/7115e856-d92f-11e4-8634-aeb4ca4d6c9d.png)

#### Arrow on mini-thread in funny place when there's no date

![screen shot 2015-04-02 at 11 47 53](https://cloud.githubusercontent.com/assets/22996/6962766/97fcb4a4-d92f-11e4-8f85-99907aafa6cf.png)

The case where a message has no data is quite rare, but probably worth taking into account.

**Comment by zarino** [comment]
Thanks @chrismytton.

Other things that need fixing:

* Messages on `/thread/<slug>` need white background, not grey background.
* …Which means content area background needs to be light grey, so messages stand out.
* …Which also means the header nav-bar and footer will need different background colours (white for navbar? dark bluegrey for footer?)
* …But make sure the homepage retains its white background, and grey navbar, as current.

And depending on time (these might be best off in separate pull requests):

* Column layout on `/threads` page (best done after the search pages etc have been merged?)
* Two-column layout in secondary section of homepage.

**Comment by zarino** [comment]
Pull request here: https://github.com/ciudadanointeligente/write-it/pull/703

**Comment by tmtmtmtm** [comment]
Closed by #703
