### ISSUE TITLE
Unprocessed {{ message.author_name }} in a.title

### ISSUE THREAD

**Issue by tmtmtmtm** [ciudadanointeligente/write-it#705]
On http://eduskunta-2.writeit.ciudadanointeligente.org/en/thread/test-112/ etc, howeving over the "Tony" in the From: line, shows an explicit "Show all messages from {{ message.author_name }}"

**Comment by tmtmtmtm** [comment]
(BTW, don't get distracted by the seemingly unprocessed HTML tags: these were added deliberately to make sure we don't Do The Wrong Thing with them.)

**Comment by chrismytton** [comment]
Fixed in https://github.com/ciudadanointeligente/write-it/commit/156d70056f123f6d1b4056ebe24ea2d1dab3c107
