### ISSUE TITLE
"Report for Abuse" button doesn't work

### ISSUE THREAD

**Issue by tmtmtmtm** [ciudadanointeligente/write-it#713]
A thread page currently has a "Report for Abuse" link that doesn't go anywhere. 

We should either make this a mailto: (per #200), or hide it until it does something.

**Comment by lfalvarez** [comment]
I think it wasn't all that clear to whom this ```mailto```should go to. I'm thinking that the simplest option is to use the owner's email, but that would leave his/her email open to the public. On the other hand we could another email of the kind ```report+averylongkey@writeit.ciudadanointeligente.org``` and that could take us some time to fix.

**Comment by tmtmtmtm** [comment]
@duncanparkes suggested adding a little popup form where the Reporter can say what they think the problem is; then we can just email that to the known email address for the Admin.

This eliminates exposing any email addresses; keeps the public-facing parts within the site rather than pushing people to email; and means we don't need a full-blown interface for managing reports.

**Comment by lfalvarez** [comment]
:+1:

**Comment by tmtmtmtm** [comment]
For now we've hidden the link. #871 deals with bringing it back.
