### ISSUE TITLE
Design for pagination of /threads

### ISSUE THREAD

**Issue by tmtmtmtm** [ciudadanointeligente/write-it#714]
http://nouabook.writeit.ciudadanointeligente.org/en/threads/, for example, has a lot of messages and is very slow.

**Comment by tmtmtmtm** [comment]
The pagination has been merged — this still needs design applied as per [comment](https://github.com/ciudadanointeligente/write-it/pull/803#issuecomment-90958350) from @zarino

**Comment by zarino** [comment]
Pull request: https://github.com/ciudadanointeligente/write-it/pull/924
