### ISSUE TITLE
Change header-bar links

### ISSUE THREAD

**Issue by tmtmtmtm** [ciudadanointeligente/write-it#732]
![header bar 2015-04-07 at 12 11 59](https://cloud.githubusercontent.com/assets/57483/7022025/6e53d3d2-dd1f-11e4-8ac8-9a2d799682e9.png)

- [x] Remove "a WriteIt instance" — a double leakage!
- [x] Remove "Search" — it doesn't exist
- [x] Remove "Sign In" — it's ultra-confusing, as there *is* no login, other than for Admins
- [x] Add link for Writing a Message

**Comment by zarino** [comment]
Pull request: https://github.com/ciudadanointeligente/write-it/pull/760
