### ISSUE TITLE
"Confirmation Required" text and design

### ISSUE THREAD

**Issue by tmtmtmtm** [ciudadanointeligente/write-it#733]
![confirmation required 2015-04-07 at 12 33 02](https://cloud.githubusercontent.com/assets/57483/7022307/4b02eee2-dd22-11e4-9022-9454d6a6aafa.png)

We need better text for this stage.

**Comment by tmtmtmtm** [comment]
We should probably also show the text of their message.

**Comment by zarino** [comment]
@tmtmtmtm – they've just seen their message on the "Preview" step immediately previous. Do they need to see it again?

For reference, my original wireframe had this on this page:

![screen shot 2015-04-07 at 15 03 11](https://cloud.githubusercontent.com/assets/739624/7024809/40ec369c-dd37-11e4-94c2-7747fafa9b16.png)

**Comment by tmtmtmtm** [comment]
If it had something like this, then it probably doesn't need to show their message again. The current version of the page is just a little too bare.

**Comment by zarino** [comment]
Pull request here: https://github.com/ciudadanointeligente/write-it/pull/906
