### ISSUE TITLE
Do /thread replies need to repeat who they're To?

### ISSUE THREAD

**Issue by tmtmtmtm** [ciudadanointeligente/write-it#750]
I'm not convinced that the replies should have the 'To' line:

![thread 2015-04-07 at 15 13 22](https://cloud.githubusercontent.com/assets/57483/7025058/d73593b8-dd38-11e4-999e-0e5a8925478c.png)

It can't vary, so is somewhat needless, but more importantly replies are to *everyone*, not just the original sender.

**Comment by zarino** [comment]
Good point! Let's get rid of the "To" line on replies!

**Comment by zarino** [comment]
Pull request: https://github.com/ciudadanointeligente/write-it/pull/781
