### ISSUE TITLE
When Writing a Message, enable clicking back to earlier stages in the flow bar

### ISSUE THREAD

**Issue by tmtmtmtm** [ciudadanointeligente/write-it#762]
You should be able to click back to earlier steps in the "Select recipients » Draft message » Preview message » Send message" so that you can, say, move back to the Preview Message stage to the Select Recipients stage.

(I'm assuming that the Django multi-page form makes this fairly trivial; if it doesn't, we can examine whether it's worthwhile)

**Comment by zarino** [comment]
Also assuming the Django form wizard makes this easy, we need to make sure that the previous steps **aren't** clickable once you've got past the "point of no return" (ie: after you've clicked "Send" at the bottom of the Preview page).
