### ISSUE TITLE
/thread page should show date and time of responses

### ISSUE THREAD

**Issue by tmtmtmtm** [ciudadanointeligente/write-it#769]
![thread 2015-04-08 at 12 10 22](https://cloud.githubusercontent.com/assets/57483/7044245/4382d8ae-dde9-11e4-8639-01173cace4a7.png)

https://github.com/ciudadanointeligente/write-it/pull/763 added the date and time for the outgoing message — it should also be displayed for responses.

**Comment by chrismytton** [comment]
Also need to fix the answer content so that it replaces newlines with `<br>` tags.
