### ISSUE TITLE
Incoming Replies cut oddly

### ISSUE THREAD

**Issue by tmtmtmtm** [ciudadanointeligente/write-it#773]
![response 2015-04-08 at 12 19 34](https://cloud.githubusercontent.com/assets/57483/7044438/598be5da-ddeb-11e4-882e-709b64065aae.png)

This includes stuff that shouldn't be there (or else is missing the rest of the quoted message)

http://eduskunta-2.writeit.ciudadanointeligente.org/en/thread/will-you-be-supporting-bill-19481-9f-2/

**Comment by lfalvarez** [comment]
I'll try to divide this into:

* Remove the ```<slug->: ``` part.
* Remove the date or possibly the name.



On 8 April 2015 at 11:50, Tony Bowden <notifications@github.com> wrote:

> Assigned #773
> <https://github.com/ciudadanointeligente/write-it/issues/773> to
> @lfalvarez <https://github.com/lfalvarez>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ciudadanointeligente/write-it/issues/773#event-276300427>
> .
>



-- 
*Felipe Álvarez*
Skype: luisfelipealvarezburgos
Twitter: @lfalvarez
Cellphone: +56973961732
*Fundación Ciudadano Inteligente*
Holanda 895 - Providencia, Santiago de Chile.
CiudadanoInteligente.cl <http://www.ciudadanointeligente.cl/> | @ciudadanoi
<http://www.twitter.com/ciudadanoi> | (56-2) 419 27 70

**Comment by tmtmtmtm** [comment]
the Name definitely needs removed too — that's leaking from the quoting of my initial message; it's not part of the response.
