### ISSUE TITLE
Instances Manager: Show the number of messages per instance

### ISSUE THREAD

**Issue by tmtmtmtm** [ciudadanointeligente/write-it#800]
![your instances 2015-04-08 at 16 39 19](https://cloud.githubusercontent.com/assets/57483/7048952/d88f47c4-de0d-11e4-84df-7aa86db034a6.png)

The "See all the messages" link should also show how many messages are in each instance

[Drive-By: Move the "Create New" link to the bottom, rather than the top?]

**Comment by chrismytton** [comment]
This just needs something like [Bootstrap buttons](http://getbootstrap.com/components/#badges) on the instance name.
