### ISSUE TITLE
Key Error when creating a New Message

### ISSUE THREAD

**Issue by tmtmtmtm** [ciudadanointeligente/write-it#810]
Since #790 has gone live, I'm now getting a KeyError when trying to create a new message:

![key error 2015-04-08 at 17 38 07](https://cloud.githubusercontent.com/assets/57483/7050020/1060f87a-de16-11e4-905d-a302e391070d.png)

**Comment by lfalvarez** [comment]
I believe it has to do with the lines https://github.com/ciudadanointeligente/write-it/blob/master/nuntium/views.py#L130-L133 and with that probably https://github.com/ciudadanointeligente/write-it/blob/master/nuntium/forms.py#L101-L110 doesn't have a ```persons``` within its fields
