### ISSUE TITLE
Message Composer: Add some client-side validation

### ISSUE THREAD

**Issue by tmtmtmtm** [ciudadanointeligente/write-it#820]
Currently, checking that you've filled in your name / email address etc looks like it's only doing server-side validation. I'm presuming it's fairly trivial to add a basic client-side check too?

**Comment by martinszy** [comment]
Idea for spam prevention: It could also have a text field hidden by CSS
that should be left empty, only bots would fill it.

Martín.

2015-04-09 19:43 GMT+00:00 Tony Bowden <notifications@github.com>:

> Currently, checking that you've filled in your name / email address etc
> looks like it's only doing server-side validation. I'm presuming it's
> fairly trivial to add a basic client-side check too?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ciudadanointeligente/write-it/issues/820>.
>



-- 
*Martín Szyszlican*
Desarrollo web usable y accesible
martinszyszlican.com

**Comment by tmtmtmtm** [comment]
@martinszy that seems like a good idea — could you open a separate ticket for that?
