### ISSUE TITLE
Admin settings pages

### ISSUE THREAD

**Issue by tmtmtmtm** [ciudadanointeligente/write-it#824]
The current admin options are the same for both WriteInPublic-based sites and API-based sites (which have their own front end):

![basic update 2015-04-07 at 13 25 20](https://cloud.githubusercontent.com/assets/57483/7023027/b6b883ac-dd29-11e4-850c-a5a0cbeba899.png)

However, many of these options only actually apply to one or the other:

field | WriteInPublic | API-driven
----- | ------------- | ----------
name  | ✓ | ✓
description | ✓ | ✘
testing mode | ✘ | ✘
moderation needed in all messages |  ✓ | ✓
messages using form | ✓ | ✘
rate limiter | ✓ | ✓
notify owner of new answer | ✓ | ✓
autoconfirm API messages | ✘ | ✓
max recipients | ✓ | ✘

* Testing mode should be disappearing as this sort of option (#823) anyway.
* "Allow messages using form" will be set by default for WIP-sites, and turning it off is largely the equivalent of deletion for a live site, so should be at the "Your instances" level instead (#751).

My proposal, which will also hopefully get around the need for WriteInPublic to override the standard WriteIt admin:

- [ ] Add (or expose if it already exists) an "Allow messages via API" option.
    - [ ] This should default to `off` for WriteInPublic-based sites (and `on` for API-driven ones)
- [ ] Default the "messages using form" to `on`, for WIP-sites, and `off` for API ones.
- [ ] Then _either_ have
    1. three separate admin tabs: one for options common to both setups, and one for each separate setup (but only two of which will ever be visible as a site will be one or the other)
    1. two admin tabs, only one of which will be visible, but with the common options duplicated across both
    1. an admin tab per option, but only the relevant ones to the current setup should be shown

My preference is probably for the third option, but I'm open to persuasion on one of the others (or something else entirely).

**Comment by wrightmartin** [comment]
After chatting this through this morning, I'll propose the following

- Present relevant settings in-situ on relevant pages.
- Hide settings that aren't relevant either at the field level, or the page level if we can (prefer page-level)
- Create a new settings page called 'about this site' for title, description and (future) slug fields

**Comment by tmtmtmtm** [comment]
#935 has taken care of the re-org. We can re-ticket anything else we need.
