### ISSUE TITLE
Attachments have vanished

### ISSUE THREAD

**Issue by tmtmtmtm** [ciudadanointeligente/write-it#830]
http://eduskunta-2.writeit.ciudadanointeligente.org/en/thread/why-did-you-approve-the-sugar-tax/ had an attachment, but we're no longer showing it.

![no attachment 2015-04-10 at 09 08 50](https://cloud.githubusercontent.com/assets/57483/7084088/3fc8602a-df61-11e4-9f4c-dd239d7d658d.png)

**Comment by tmtmtmtm** [comment]
These were introduced in https://github.com/ciudadanointeligente/write-it/pull/565 but presumably disappeared in the redesign (although I'm surprised this didn't trigger a test failure).

**Comment by zarino** [comment]
Pull request here: https://github.com/ciudadanointeligente/write-it/pull/836

![screen shot 2015-04-10 at 12 26 41](https://cloud.githubusercontent.com/assets/739624/7086833/4f435656-df7d-11e4-9903-8a0e17d6bc9f.png)

**Comment by lfalvarez** [comment]
Oh this doesn't trigger a test failure since it is mostly a front end design and not behavior.
