### ISSUE TITLE
Create a Write-It instance link on /en/instances doesn't work

### ISSUE THREAD

**Issue by chrismytton** [ciudadanointeligente/write-it#832]
When there are no existing instances in the database the **Create a Write-It instance** link doesn't do anything.

![screen shot 2015-04-10 at 11 47 06](https://cloud.githubusercontent.com/assets/22996/7086322/59f7f09e-df77-11e4-8da2-c6e3c46184f2.png)

**Comment by tmtmtmtm** [comment]
This is for a completely fresh WriteIt setup (i.e. this won't happen on the live site?) — or when a new admin has just created an account, and doesn't have any instances of their own yet?

**Comment by tmtmtmtm** [comment]
Ah, I understand this now. I never realised before that page could even have a link like this! Fixed in #864!
