### ISSUE TITLE
Home Page: Don't show "Recent Messages" if there are none

### ISSUE THREAD

**Issue by tmtmtmtm** [ciudadanointeligente/write-it#866]
Either explicitly say that there are no messages, or don't show the heading.

![no recent messages 2015-04-11 at 21 10 24](https://cloud.githubusercontent.com/assets/57483/7103096/423c3ec4-e08f-11e4-829f-e99c86421c7b.png)

**Comment by zarino** [comment]
I'd hide the heading.

In fact, I'd be inclined, for an MVP, to remove that entire grey section of the instance_detail.html page. It'll be simpler than conditionally showing and hiding, and we can always reinstate it once we have more time to think about what should be there.
