### ISSUE TITLE
Check "Notify owner" emails

### ISSUE THREAD

**Issue by tmtmtmtm** [ciudadanointeligente/write-it#868]
I haven't been able to check the "Notify owner when new answer" emails. I'm presuming this is something to with the site being in testing mode. But we need to make sure they work / make sense / etc.

**Comment by tmtmtmtm** [comment]
It might be possible, even sensible, to implement these as Bcc on the similar notification to the original sender...

**Comment by duncanparkes** [comment]
To all intents and purposes, a BCC is what happens. The instance owner is added to the list of people subscribed to the answers to a message, and gets the same email as everyone else.

**Comment by tmtmtmtm** [comment]
Ah, OK, that makes sense. That's presumably why I'm only getting one copy then, too?

But if they're just the same message, then there's nothing much to check, so closing for now unless something specific comes up.
