### ISSUE TITLE
'edit' button on multiple sources opens the edit dialogue for the first data source only

### ISSUE THREAD

**Issue by wrightmartin** [ciudadanointeligente/write-it#894]
in manage/settings/sources/

**Comment by tmtmtmtm** [comment]
Fixed by #854

**Comment by wrightmartin** [comment]
thanks tony, I did search first but it didn't find your PR

**Comment by tmtmtmtm** [comment]
I've been trying to apply at least some degree of structure to the Issue tickets, as I also keep raising tickets that I was sure that existed, but couldn't find (often only to discover the actual ticket again later!) 

The original of this (#851) has a "Source Manager" prefix — definitely open to other suggestions for making them easier to find! Maybe liberal use of keywords at the bottom of the descriptions for easier searching?
