### ISSUE TITLE
Can PopIt Data import be done on demands, rather than only weekly

### ISSUE THREAD

**Issue by paullenz** [ciudadanointeligente/write-it#910]
At the moment I am not sure (but I think) that the PopIt import is a one time thing, or if not I am not sure how I can hit *reimport* if I know that data has been updated, added to etc

Ah - I now see that it updated weekly - I would like a button to hit to say "update now" as well

**Comment by tmtmtmtm** [comment]
Clicking "Edit" on the data source lets you change how often it updates, or indeed to "Fetch new data now?"

I'm guessing that if you got to the point of seeing that it updates weekly, you were already on the right page, but just didn't see the Edit button?

(This is very useful feedback, as we'll be applying the new design to all the admin pages tomorrow!)

**Comment by paullenz** [comment]
Ahhh - I had see the edit link, but I hadn't realised that could also lead me to refreshing the data 

Oddly I found a way around it by simply trying to add in the same data source again as though it was new (nice that it caught that and didn't create a new WI instance)

**Comment by tmtmtmtm** [comment]
I've ticketed making this easier to find at #945, but closing this one because the functionality does already exist.
