### ISSUE TITLE
Update URLs of settings page

### ISSUE THREAD

**Issue by wrightmartin** [ciudadanointeligente/write-it#936]
Part of #935 (template files need to be renamed too)

/manage/settings/ratelimiter/ - > /manage/messages/settings/
/manage/settings/maxrecipients/ -> /manage/recipients/settings/
/manage/settings/apiautoconfirm/ -> /manage/api/settings/

**Comment by tmtmtmtm** [comment]
@wrightmartin The URL changes have been merged; template renaming can happen in a separate change if you give me a list of before/after pairs like the URLs above.

**Comment by wrightmartin** [comment]
@tmtmtmtm sorry, a change related to my updated PR - /manage/settings/ratelimiter/ - > /manage/messages/settings/ is now /manage/settings/answernotification/ - > /manage/messages/settings/
