### ISSUE TITLE
Admin section footer is unstyled

### ISSUE THREAD

**Issue by tmtmtmtm** [ciudadanointeligente/write-it#975]
Public site:
![public footer 2015-04-15 at 12 11 01](https://cloud.githubusercontent.com/assets/57483/7157536/8de8124a-e368-11e4-8c64-9436e0452619.png)

Admin section:

![admin footer 2015-04-15 at 12 10 50](https://cloud.githubusercontent.com/assets/57483/7157537/8dedff98-e368-11e4-85ef-ac743b6fdd23.png)

**Comment by zarino** [comment]
Pull request:  https://github.com/ciudadanointeligente/write-it/pull/1038
