### ISSUE TITLE
Make sure that email subjects don't contain "WriteIt"

### ISSUE THREAD

**Issue by tmtmtmtm** [ciudadanointeligente/write-it#982]
Some of the emails are being prefixed with "[WriteIT]"

Others are saying things like "Please confirm your WriteIt message to..."

**Comment by chrismytton** [comment]
I've changed `EMAIL_SUBJECT_PREFIX` from `[WriteIT] ` to `''` on the production server in `~writeit/write-it/writeit/local_settings.py`. So any emails using that setting will no longer have that prefix.

**Comment by duncanparkes** [comment]
I can't see any mention of WriteIt in the templates for confirmation email, new answer notification, and the mailit message.

**Comment by tmtmtmtm** [comment]
including subjects? As of this morning confirmation emails were still showing "Please confirm your WriteIt message to..."

**Comment by duncanparkes** [comment]
Yes, including subjects. I wonder if that's the change tho @chrismytton mentions.

**Comment by duncanparkes** [comment]
@tmtmtmtm You're quite right. I must have forgotten no `-r` my grep.
